//
// /**
//  * Offer
//  */
//
// /**
//  * Module Dependencies
//  */
//
// // var crypto    = require('crypto');
// // var mongoose = require('mongoose');
// //
// // var offerSchema = new mongoose.Schema({
// //     id: String,
// //     name: String,
// //     amount: Number,
// //     maximumRides: Number
// // });
// //
// //
// //
// //
// // module.exports = mongoose.model('Offer', offerSchema);
//
//
// /**
//  * Offer
//  * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
//  *
//  * OpenAPI spec version: 0.0.0
//  *
//  *
//  * NOTE: This class is auto generated by the swagger code generator program.
//  * https://github.com/swagger-api/swagger-codegen.git
//  * Do not edit the class manually.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License");
//  * you may not use this file except in compliance with the License.
//  * You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software
//  * distributed under the License is distributed on an "AS IS" BASIS,
//  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  * See the License for the specific language governing permissions and
//  * limitations under the License.
//  */
//
// (function(root, factory) {
//     if (typeof define === 'function' && define.amd) {
//         // AMD. Register as an anonymous module.
//         define(['ApiClient'], factory);
//     } else if (typeof module === 'object' && module.exports) {
//         // CommonJS-like environments that support module.exports, like Node.
//         module.exports = factory(require('../ApiClient'));
//     } else {
//         // Browser globals (root is window)
//         if (!root.Offer) {
//             root.Offer = {};
//         }
//         root.Offer.Offer = factory(root.Offer.ApiClient);
//     }
// }(this, function(ApiClient) {
//     'use strict';
//
//
//
//
//     /**
//      * The Offer model module.
//      * @module model/Offer
//      * @version 0.0.0
//      */
//
//     /**
//      * Constructs a new <code>Offer</code>.
//      * @alias module:model/Offer
//      * @class
//      */
//     var exports = function() {
//         var _this = this;
//
//
//
//
//
//     };
//
//     /**
//      * Constructs a <code>Offer</code> from a plain JavaScript object, optionally creating a new instance.
//      * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
//      * @param {Object} data The plain JavaScript object bearing properties of interest.
//      * @param {module:model/Offer} obj Optional instance to populate.
//      * @return {module:model/Offer} The populated <code>Offer</code> instance.
//      */
//     exports.constructFromObject = function(data, obj) {
//         if (data) {
//             obj = obj || new exports();
//
//             if (data.hasOwnProperty('id')) {
//                 obj['id'] = ApiClient.convertToType(data['id'], 'String');
//             }
//             if (data.hasOwnProperty('name')) {
//                 obj['name'] = ApiClient.convertToType(data['name'], 'String');
//             }
//             if (data.hasOwnProperty('amount')) {
//                 obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
//             }
//             if (data.hasOwnProperty('maximumRides')) {
//                 obj['maximumRides'] = ApiClient.convertToType(data['maximumRides'], 'Number');
//             }
//         }
//         return obj;
//     }
//
//     /**
//      * @member {String} id
//      */
//     exports.prototype['id'] = undefined;
//     /**
//      * @member {String} name
//      */
//     exports.prototype['name'] = undefined;
//     /**
//      * @member {Number} amount
//      */
//     exports.prototype['amount'] = undefined;
//     /**
//      * @member {Number} maximumRides
//      */
//     exports.prototype['maximumRides'] = undefined;
//
//
//
//     return exports;
// }));
//
//
